# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoloProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downvoters', models.ManyToManyField(related_name='downvoter', to=settings.AUTH_USER_MODEL)),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op', to=settings.AUTH_USER_MODEL)),
                ('upvoters', models.ManyToManyField(related_name='upvoter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
