# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='figures/')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figure_op', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='holoproject',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holoproject',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/projects/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holoproject',
            name='image',
            field=models.ImageField(blank=True, upload_to='captures/'),
        ),
        migrations.AddField(
            model_name='holoproject',
            name='figures',
            field=models.ManyToManyField(related_name='figure', to='projects.Figure'),
        ),
    ]
